title: Default
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      fields:
        content:
          fields:
            header.background_image:
              type: filepicker
              label: Background Image
              preview_images: true
              description: 'If not specified, this defaults to the first image found in the page''s folder'
